### ISSUE TITLE
icalendar feeds not working/empty

### ISSUE THREAD

**Issue by bklang** [Gig-o-Matic/GO3#258]

**Comment by aaronoppenheimer** [comment]
Two things to fix this:

1 - there was a problem with the default .env file which was not causing the problem but made it hard to test. See https://github.com/Gig-o-Matic/GO3/pull/259

2 - there are a bunch of hourly and daily tasks that, among other things, update cal feeds.

If the env file is set to generate calfeeds "dynamically" they're made as soon as they're requested. But because it can take time and you don't want to do it every time a calendar feed is requested, there's a caching system enabled by default. When a gig is created or altered, every member of the band has a "dirty" flag set. Then once/hour, the system goes through and creates a calfeed for every member with the flag set, and stores it in the "calfeeds" directory. (Maybe in future they shouldn't be stored locally?)

In order to make that happen, you need to set up the tasks. "python manage.py schedule_tasks" will create the necessary items. Look in stats/management/commands/*.py to see how it is set up.

Note: in the old gig-o, this was done by setting up a repeating task in the google app engine that would access a particular URL on a schedule, and the handler for that URL would do the work. There is clear evidence that go3 was set up to do that too, but I believe it can be ripped out. This is in member/helpers.py (and member/urls.py).

Note note: the tasks are all run as async tasks so qcluster must be running.

**Comment by bklang** [comment]
I don't think this is done, or at least, it's still not working on the new site. I did set up the scheduled tasks (thank you), but my calendar feed is still empty. Maybe this has something to do with the storage issue you mentioned?

**Comment by aaronoppenheimer** [comment]
Yes, I think to store files locally we have to use "spaces" or some other remote file storage mechanism. [Some info here](https://blog.devgenius.io/django-digitalocean-spaces-a12b4a053628).

**Comment by aaronoppenheimer** [comment]
@bklang This is still not working for me. Did you flip the "dynamic calfeed" switch, or should we not do that?

**Comment by bklang** [comment]
We can try dynamic calfeed. I'm am concerned about the load it will create, but so far we don't have that problem. If load does become a problem, we can switch to the Digital Ocean Spaces to cache the files. It'll add a bit to the monthly cost, but not bad.

I've enabled it on the live site.

**Comment by bklang** [comment]
This is working. We can revisit calendar data caching in the future.
