### ISSUE TITLE
Band migration did not copy gig contacts

### ISSUE THREAD

**Issue by nocturne-mit** [Gig-o-Matic/GO3#297]
Some bands, like mine, have a lot of different contacts for different gigs, but that data isn't being copied automatically when the band gets migrated. It would be a big time-saver if that info got copied when the gigs are copied.

**Comment by aaronoppenheimer** [comment]
We can keep thinking about it, but it's non-trivial because the databases are completely different - figuring out which member to point to in the new database is tricky. But not impossible.

**Comment by bklang** [comment]
I'm going to close this as "not planned" due to the effort required. Most bands that we have imported so far have had 5 or fewer future gigs. I appreciate that it is inconvenient for admins during this migration, but it's a one-time pain and our volunteer developer hours are limited.  But thank you for the suggestion!
