### ISSUE TITLE
Any time set to "??" makes all times disappear from Gig Info page

### ISSUE THREAD

**Issue by nocturne-mit** [Gig-o-Matic/GO3#300]
If I save a gig details page with "??" in a time field, the Gig Info page omits all time information for that gig.

**Comment by nocturne-mit** [comment]
Also, when gigs are still under negotiation it's not unusual for us to have a solid call time and end time, but no precise start time. (Or vice versa.) It would be great if the Gig Info page displayed whichever times were set, and either skipped, or displayed some kind of blank value for the unspecified times.

Would it work to allow storing a NULL time value?

**Comment by aaronoppenheimer** [comment]
That is the intent - that it shows only the times you have set, and otherwise doesn't. It just wasn't implemented well! But should be straightfoward to fix.

**Comment by bklang** [comment]
One reason this has unexpected behavior: the dates & times are displayed in the UI as separate fields, but are stored in the DB as a single date+time value. This is why we can't store a NULL time when a date is specified. If we want to provide the flexibility the UI implies, we need to separate the storage of the dates and times.  I think this is worth doing, but is a non-trivial change.

**Comment by aaronoppenheimer** [comment]
Right. I'm trying to think through the options, like flags to specify "there is no time with this date" but in that case we might as well go back to how go2 did it: time is a text field, there's a helper to set the time but if you want to type in "after lunch" you can. The only thing this really affects is the calendar feed. Go2 tried to parse the string as time, and if it couldn't it just made the event show at midnight (or maybe make it a full-day event, can't remember). We could just go back to that.

**Comment by bklang** [comment]
I really like the time field being a real time value. It enables the calendar integration and helps with things like reminders. If a gig's time is spongy, the Date Notes field is a good solution to that (while leaving the actual time fields empty). I think the best route is to improve the UI for collecting times (and allowing them to be empty), rather than weaken the data type to a string.

On the backend, this means creating separate fields to store date and time, and migrating the data into the new columns.
On the frontend, I imagine keeping the date fields as-is, and providing a checkbox that says "Time unknown" or Time flexible". When checked, it hides the time fields, and leaves them undefined.
For the calendar feed, this means showing the gig as an "All Day" event.

**Comment by aaronoppenheimer** [comment]
Agreed. I think also a checkbox for "all day event" which also hides the times. This allows the agenda page to show "all day"

**Comment by bklang** [comment]
Closing this in favor of #337 which contains our plans to address this
