### ISSUE TITLE
Migration welcome emails can be user-friendlier

### ISSUE THREAD

**Issue by bklang** [Gig-o-Matic/GO3#316]
We've had a few people complain about the links in the email not working. This is almost always because the link has expired.  I suggest two improvements:

* Make the link last longer (1 week)
* Put a link (or even the form) on the "invalid link" error page that prompts the user to request a password reset

**Comment by aaronoppenheimer** [comment]
Hm - I can't actually find a place where invitations timeout. It looks like the "expired" page is shown as a result of [here](https://github.com/Gig-o-Matic/GO3/blob/745f10593903cb2742c19cca713e720f1552e716/member/views.py#L277) but that means no invite could be found. And invites don't seem to be deleted except by clicking the 'delete invitation' link in the band page. Are you sure the problem is links expiring?

**Comment by bklang** [comment]
Sorry, I should have been more clear: when I import users by migration, I'm [manually triggering a password reset email](https://github.com/Gig-o-Matic/GO3/blob/de47932f7871017b4509dd3877306f9b6a79aa38/migration/helpers.py#L24) with a special template. The import process actually creates a user, which is different than the invitation process, which does not.

I've had reports from 5 or so users who reported that the link was no longer working, and who were subsequently successful gaining access via password reset. But I've never actually seen the problem myself, so I made the assumption that the reset link expired.

**Comment by aaronoppenheimer** [comment]
I see! Makes sense. We can make it longer for now - it’s just a setting. Apparently the default is less than a day.

https://stackoverflow.com/questions/21155264/setting-expiration-time-to-django-password-reset-token#22522549

**Comment by bklang** [comment]
Thanks! TImeout increased in #320
