### ISSUE TITLE
Trying to invite an existing Gig-O user to join a band doesn't work right

### ISSUE THREAD

**Issue by bklang** [Gig-o-Matic/GO3#339]
This exception is probably related: https://gig-o-matic.sentry.io/issues/5081148591/

**Comment by aaronoppenheimer** [comment]
I can't reproduce this. The error message from sentry is the one [here](https://github.com/Gig-o-Matic/GO3/blob/b5879dd030775bf689beb727bd6e5412d28dbbe0/member/forms.py#L21) which fires if someone accesses an invitation (either because they got an invitation from a band or because they signed up themselves, which uses the same mechanism) but the member already exists in the database.

This seems like it could be "band invites member; member signs up and clicks the link in the signup email; member later clicks the link in the band invitation email" but that doesn't seem to be it - if you do that you just join the band. I can't make a situation where there's an existing member and clicking an invitation results in the member trying to be created again.

I did find that if I created a member by email, did it again, and then accepted the first invitation, logged out, and accepted the second invitation, the gig-o tells me I have successfully joined the band "none" - which is the above mechanism, which expects a second invitation to be from a band. Doesn't seem to have any bad effects but should be addressed.

**Comment by bklang** [comment]
Ok, thanks for investigating. I'm going to assume that the exception occurred when the user clicked on an old invitation link and is not an actual bug. The user in question was definitely having trouble being confused about GO2 vs. GO3, which I'm sure didn't help. I'll focus on #340 to help transition users, especially those in more than one band, keep things straight.
