### ISSUE TITLE
Consider more customization options for the agenda page

### ISSUE THREAD

**Issue by aaronoppenheimer** [Gig-o-Matic/GO3#385]
It might be cool to allow users to customize the agenda page with different options, like

- show everything in one block
- split out "responded" vs. "unresponded" (which is the behavior now)
- split out "confirmed" vs. "confirmed"
- sort by band
- show cancelled gigs in their own place

**Comment by Oscillope** [comment]
I hope it's OK to put some feedback on the new agenda page layout here. Personally I really liked having the "single view for everything" where I could see both upcoming gigs and gigs I haven't responded to on the same page. It's nice to not have to have two places to check. I do like the ability to filter the schedule by band, though.

What would you think about making them additive filters/selectors instead of radio buttons (e.g. you could click on both "Upcoming Gigs" and "Needs Response" to see everything in one view)? I think that'd provide a lot of the desired flexibility while still allowing people to choose the old behavior if they want it.

**Comment by aaronoppenheimer** [comment]
Hiya,

The "all upcoming gigs" option does show you the gigs you haven't responded to; it's just all in one list. The "needs response" option filters and shows you only the ones that need response. I've had many requests for a "just how them in a single list" version but I also like being able to just see the stuff I need to respond to. This gives both. I thought about a bunch of different ways to handle it and the new version seemed to be the best balance of configuration vs simplicity.

You can revert back to the old layout using the "use old layout" option in your preferences if you miss it!

A

**Comment by Oscillope** [comment]
Ooooh! I totally did not notice that it shows unresponded gigs in the same list. Nor did I notice the option to revert the layout (FWIW the new option does not show up in the options summary on my profile page, only if I specifically navigate into the preferences submenu). I do think having unresponded gigs show up at the top of the list is more convenient (and the bandmates I've talked to feel the same), but as long as that option sticks around I'm happy.
Thanks for the explanation!

**Comment by aaronoppenheimer** [comment]
Maybe there could be a badge showing the number of unresponded gigs in the button so if you're looking at the list of everything you can still see that there are a few that need your attention. Will think about it!

**Comment by aaronoppenheimer** [comment]
Addressed with the fitering mode.
