### ISSUE TITLE
Caught error: value too long for type character varying(200)

### ISSUE THREAD

**Issue by bklang** [Gig-o-Matic/GO3#386]
Appeared to happen when a very long comment was left on a gig plan, I think.

https://app.rollbar.com/a/Gig-O-Matic/fix/item/Gig-O-Matic/8/occurrence/402279617451#detail

**Comment by aaronoppenheimer** [comment]
That's the problem, all right. There's a 200-character limit in the model. The goal isn't to paste in paragraphs, but we could take the character limit off this. Otherwise, and I think this is better, we can just impose the limit on the front-end and put in a check on the back-end so the database doesn't get unhappy.

**Comment by aaronoppenheimer** [comment]
Suggested fix in  #391
