### ISSUE TITLE
Add a Series of Events Emails

### ISSUE THREAD

**Issue by SethPate** [Gig-o-Matic/GO3#396]
"Add A Series of Events" is a really helpful box:

<img width="247" alt="image" src="https://github.com/Gig-o-Matic/GO3/assets/17327269/f7e77fcd-fb30-4c2d-a320-eba6e0c5ac24">

But when combined with "Email Members About This Gig", only the *last* event created is sent to members. Maybe only one email is a sane and good idea! But in that case it should be the first event.

**Comment by aaronoppenheimer** [comment]
Will check it out!

**Comment by aaronoppenheimer** [comment]
A few notes on this:

- I think [this](https://github.com/Gig-o-Matic/GO3/blob/03a813ea70a492ea94df449db449562fe1c19724/gig/forms.py#L191) is the problem - we're actually altering the date of the gig that the form refers to, so when the view processes it the date has been set to the last date
- The form probably shouldn't be doing this processing - should go in the view, I think.
- We could consider sending out a notification for the first gig and including a note "this is the first of a series"; or we could send out a notification for every gig (seems like a terrible idea); or we could have the link in the email allow you to say "yes" or "no" for every gig in the series.
- I also think it would be good to have the gigs in the series be linked together so if you change info on one you have the option of changing the info on all the following instances. Eventually, would be nice.

**Comment by aaronoppenheimer** [comment]
Addressed by #405, which fixes things so the email is about the first gig instead of the last.

Should continue to work on this to add features as listed above.

**Comment by nocturne-mit** [comment]
I got email notification today about a series-of-gigs entry. I had several issues with it, but the biggest is that the notification email in no way indicated that it was connected with a series of gigs, so I thought there was only one new gig created:
* The creation email did not mention "series" or any of the dates other than the first gig date
* The creation email contained yes/no RSVP links that only pertained to the first gig date
* The creation email contained a "Gig info page" link that only linked to the first gig date
* When you click the "gig info page" link, the gig info page you see has no built-in indicators that it's part of a gig series.

To improve this, one idea for a low-effort enhancement would be for "gig series" creation emails to clearly state that they're for a gig series, and to state the first and last gig dates, and probably not have yes/no links for ANY gig date, and either have no "gig info" links, or to have a separate "gig info" link for each separate gig event.

If gig-series events work just like any other gig after they're created (e.g. each event can be edited separately) then it seems fine for subsequent event-update emails to work just like any other gig.

Sure, if you wanted to get very fancy, you could support gig-series as its own first-class entity with special UI workflows for display/editing/notification of the gig. But this kind of whizbang UI integration doesn't seem very important to me, as long as the underlying usability issues are fixed in some other way (e.g. per my suggestion).

**Comment by aaronoppenheimer** [comment]
Addressed in #470
