### ISSUE TITLE
Past gigs still showing up after end date

### ISSUE THREAD

**Issue by bklang** [Gig-o-Matic/GO3#419]
Reported via email:

> I notice that a "gig" (actually a rehearsal) from yesterday is still up today on the new gig-o-matic. It isn't seeming to "expire" / disappear like it should. (This is for Filthy FemCorps). 

<img width="388" alt="Screenshot 2024-04-08 at 7 00 27 PM" src="https://github.com/Gig-o-Matic/GO3/assets/167131/bfd330fe-3983-4a3c-9892-c8c7789ea3d2">

I suspect this is a timezone issue, as the end date is the following day UTC:

<img width="198" alt="Screenshot 2024-04-08 at 7 03 22 PM" src="https://github.com/Gig-o-Matic/GO3/assets/167131/4071034c-66b8-4035-aa1d-307664a3a45d">

**Comment by aaronoppenheimer** [comment]
It's actually not a timezone problem, it's that I took the easy way out when I "fixed" this the other day. The problem is [here](https://github.com/Gig-o-Matic/GO3/blob/b1e78e25bf5dbbef71b3be3c932aabf5bb69e5b5/gig/models.py#L47) - gigs are in the past if they're 24 hours past their call date (or end date if they have one). But that means tonight's gig will be visible tomorrow morning.

The right thing to do, I think, is localize to the current timezone and compare days. If a gig happened earlier "today" it's fine if it's on the schedule, but if it happened "yesterday" it shouldn't be. We don't want gigs disappearing immediately after the call time, for instance, because if the set time is later you still want it on the gig-o. I think "today/tomorrow" for a local definition is the right thing.

I will update it.

**Comment by aaronoppenheimer** [comment]
OK, so this is where is gets ugly. "Yesterday" means something different wherever you are. If I make a gig in the evening Eastern, it will be "tomorrow" UTC, so "yesterday" will actually mean today. I need to know the user's timezone in order to calculate the threshold time before which gigs are "yesterday."

A hacky way to do it is just use the first band the member is associated with - whatever timezone it uses, call that the member's time zone. If I do that, it works. But if the member travels someplace "yesterday" will change.

What do you think?

**Comment by aaronoppenheimer** [comment]
Maybe better to just say "the gigs disappear a few hours after they're over" which will usually mean you're done looking at them. They always show up in the archive immediately anyway.

**Comment by bklang** [comment]
> "Yesterday" means something different wherever you are. If I make a gig in the evening Eastern, it will be "tomorrow" UTC, so "yesterday" will actually mean today. I need to know the user's timezone in order to calculate the threshold time before which gigs are "yesterday."

I think you could get away with using the band's timezone instead of the user's timezone. Gigs will always be local to the band, regardless of where the user is. This doesn't make things much easier though, because you still have to somehow query while tracking multiple timezones.



> Maybe better to just say "the gigs disappear a few hours after they're over" which will usually mean you're done looking at them. They always show up in the archive immediately anyway.

This is probably the best answer.  To avoid the confusion about "Upcoming Gigs" with a "yesterday" date, what if we add a third section at the top for "Happening Now". Then at least it's less confusing if "now" extends in to the following day, like a grace period.

**Comment by aaronoppenheimer** [comment]
OK, updated the threshold time so gigs get 4 hours after call/set/end - whichever is latest - to appear on the schedule page. Addressed in pr #424

**Comment by bklang** [comment]
Love it - much simpler than my solution. Thanks!
