### ISSUE TITLE
"Hide Canceled Gigs" changes time for other gigs in Schedule view

### ISSUE THREAD

**Issue by SethPate** [Gig-o-Matic/GO3#427]
Recently turned on the (very helpful) feature to hide cancelled gigs, but every other gig is set three hours behind. Maybe a time zone thing? All-day gigs have a date that is off by one day (early).

An example gig; the time here is correct:
<img width="751" alt="image" src="https://github.com/Gig-o-Matic/GO3/assets/17327269/c70a9627-1c89-415d-a24f-8250a869a8c1">
Displays as:
<img width="718" alt="image" src="https://github.com/Gig-o-Matic/GO3/assets/17327269/35dab3aa-1573-4c6e-ac81-d2b7198f5ef2">

**Comment by aaronoppenheimer** [comment]
Hi all - that PR is the problem because it's the first time we've put the time on the schedule page, revealing the issue. The trouble seems to be that the "schedule" page doesn't activate the user's timezone before displaying those times. I have been able to replicate the behavior.

Try this: if the time looks bad on the schedule page, click on a gig, verify its time is right, and then click on the "gig-o-matic" logo to go back to the schedule page (don't just hit 'back'). Are the times correct now? That's how it's working for me in the development environment.

I am pushing through a fix that should help on the schedule page - though I also note that the times aren't always correct on the "calendar" page, probably for a similar reason. Will take a look today!

**Comment by SethPate** [comment]
Clicking the gig-o-log-o does correct the times for me.

**Comment by aaronoppenheimer** [comment]
Great. I just pushed through a change that should fix it. To make sure, you could log all the way out of the gig-o and back in - when you first see the schedule page it should show the times correctly.

thanks for your help!

A
