### ISSUE TITLE
"Duplicate" button gives "403 forbidden"

### ISSUE THREAD

**Issue by DanCodiga** [Gig-o-Matic/GO3#484]
occurs on mobile, desktop, multiple browsers

**Comment by aaronoppenheimer** [comment]
Dan, which band is it happening for?

This is likely because the band has "any user can manage gigs" true but "any user can create gigs" false. The logic in the template shows the "duplicate" button because of the "manage" permission but it should really only show it for the "create" permission. When a non-admin user goes to duplicate the gig, that's a permission violation because they're trying to create. The fix will be to update the logic in the template.

**Comment by DanCodiga** [comment]
Okay thanks for the quick reply. 
This is for Jamaica Plain Honk Band.

**Comment by aaronoppenheimer** [comment]
Hm. That band is set with both "create" and "manage" set to true, so something else is going on. Will investigate.

**Comment by aaronoppenheimer** [comment]
addressed in #485 - should be fixed now!
