### ISSUE TITLE
Gig Archive used to show all gigs (past/future and "cancelled")

### ISSUE THREAD

**Issue by kalebabebe** [Gig-o-Matic/GO3#513]
Not sure if I'm misremembering, but old gigo used to show _every_ gig for a band, including future gigs and cancelled gigs (pretty sure it didn't show trashed/deleted though)

Example cancelled gig - https://www.gig-o-matic.com/gig/2686/

Archive - https://www.gig-o-matic.com/band/55/archive

**Comment by aaronoppenheimer** [comment]
Hi Kaleb,

I don't think the old gig-o showed future gigs in the archive, though I'll check. Once a gig is past its date, whether it has been cancelled or not it should show up there. In your case, because you have "hide cancelled gigs" set in your preferences, you won't see it on your calendar because it hasn't happened yet - but after tomorrow it will show up in the archive.

I guess I don't see a reason *not* to have the archive show future gigs as well as past gigs, though the idea of "archive" is meant as "keeps your history." I'll think about it!

A

**Comment by kalebabebe** [comment]
>  In your case, because you have "hide cancelled gigs" set in your preferences, you won't see it on your calendar because it hasn't happened yet - but after tomorrow it will show up in the archive.

Ahh forgot about this setting, thanks!
