### ISSUE TITLE
all-day gig for Feb 1 2025 displays with completely wrong dates

### ISSUE THREAD

**Issue by nocturne-mit** [Gig-o-Matic/GO3#526]
https://www.gig-o-matic.com/gig/3162 was originally entered as being a full-day event occurring on 02/01/2025.
It displays as "01/31/2025 (Friday)" , although when you go back to edit, it still shows 02/01/2025 in the edit field.

Could this be related to February being in a different daylight-savings status than we are currently?

**Comment by nocturne-mit** [comment]
And after editing to be a multi-day gig from 1/31 to 2/1 2025, it's displaying as 1/30 to 1/31 instead.

**Comment by aaronoppenheimer** [comment]
Ugh - sorry, Eric! Will figure it out.

Technical note to myself: This is related to something we've seen before - when saving a date with a timezone, the database shifts the time into UTC except it subtracts four minutes. So a date of 2/1/25 at 0:00 Eastern turns into 2/1/25 at 4:56 UTC. So when the gig is read back OUT of the database and shifted into Eastern, it shows up as 1/31/25 at 11:56pm. Since it's a full-day gig it's just treated as 1/31/25. If you edit and save the gig, it shifts back ANOTHER day. Every time. I wonder why other people haven't seen/reported this?

**Comment by aaronoppenheimer** [comment]
Some info here: https://stackoverflow.com/questions/63359499/how-can-i-force-pytz-to-use-currently-standard-timezones

**Comment by aaronoppenheimer** [comment]
Addressed in #527 

@nocturne-mit Eric - see if it's working for you now?

**Comment by nocturne-mit** [comment]
It seems to be working correctly for this gig now, thanks!
