### ISSUE TITLE
In-progress gigs cannot be edited

### ISSUE THREAD

**Issue by Oscillope** [Gig-o-Matic/GO3#557]
This is very much an edge case, but I figured it'd be worth documenting/asking if it's worth fixing. No part of a gig page can be edited once the gig's call/start time passes, since it validates that the time must be in the future. I was trying to edit a set list, and couldn't change it unless I also set the call time to a time in the future. Would it be difficult to bypass the "time is in the future" validation if the time hasn't changed?
![IMG_3421](https://github.com/user-attachments/assets/356c029c-3195-43a2-a306-86444bbb26bb)

**Comment by bklang** [comment]
Thanks for the report! The fix for this is now live.

Note that gigs will still be archived after the gig is over. Archived gigs are not editable, so this allows for editing details (other than start time) after the gig has started up until it gets archived. I think that's right, but let us know if you expected something else.

**Comment by JasonRosenmansonos** [comment]
Thanks so much! That sounds perfect.

**Comment by Oscillope** [comment]
Thanks so much! that sounds perfect.
